'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TokiDriftApplication.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _161a6dd8fff8fad3852cdb992e16f102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("161a6dd8fff8fad3852cdb992e16f102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Antipasti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Antipasti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Chirashi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chirashi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property f914c4c93bbdcd9d60995acda108a77d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f914c4c93bbdcd9d60995acda108a77d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Gunkan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gunkan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Hosomaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Hosomaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Nigiri() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Nigiri", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PiattiCaldi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PiattiCaldi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Sashimi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sashimi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property synthvaporwave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("synthvaporwave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Temaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Temaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift33() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift33", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift34() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift34", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift35() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift35", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift38() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift38", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift39() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift39", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TokiDrift40() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TokiDrift40", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una risorsa localizzata di tipo System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Uramaki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uramaki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
